# Common parameters for all controllers
test_num: 100             # number of tests
n_steps: 200              # number of time steps in each test
cpu_num: 20
regenerate: true          # regenerate data

nlp_max_iter: 150
qp_max_iter: 150
solver_mode: 'BALANCE'    # HPIPM mode, can be --> 'BALANCE', 'ROBUST', 'SPEED', 'SPEED_ABS'
alpha: 2
conv_tol: 1e-3            # convergence tolerance for the task

# Naive Controller
naive:
  dt: 5e-3
  T: 0.175

# Soft Terminal Controller
st:
  dt: 5e-3
  T: 0.175
  ws_t: 1e4

# Soft Terminal With Abort Controller
stwa:
  dt: 5e-3
  T: 0.175
  ws_t: 1e4

# Hard Terminal With Abort Controller
htwa:
  dt: 5e-3
  T: 0.175
  ws_t: 1e4

# Receding Controller
receding:
  dt: 5e-3
  T: 0.175
  ws_r: 1e4
  ws_t: 1e4

parallel:
  dt: 5e-3
  T: 0.175
  ws_r: 1e4
  ws_t: 1e4

parallel2:
  dt: 5e-3
  T: 0.175
  ws_r: 1e4
  ws_t: 1e4

# Safe Abort OCP
abort:
  dt: 5e-3
  T: 0.18
  q_dot_gain: 1e6