n_steps: 100
test_num: 100
cpu_num: 20
regenerate: true

model:
  l1: 0.8
  l2: 0.8
  l3: 0.8
  g: 9.81
  m1: 0.4
  m2: 0.4
  m3: 0.4
  q_min: -0.25      # defined as fraction of pi
  q_max: 0.25
  dq_min: -10
  dq_max: 10
  u_min: -10
  u_max: 10

simulator:
  dt: 5e-3
  integrator_type: 4  # RK4

controller:
  dt: 5e-3
  T: 0.175
  x_ref: [3.8769, 3.14, 3.14, 0, 0, 0]
  solver_type: 'SQP'  # 'SQP_RTI'
  nlp_max_iter: 100
  qp_max_iter: 100
  safety_margin: 2
  ws_t: 1e4
  ws_r: 1e4
